geometry:
  nx: 25            
  ny: 5             
  length: 2.0       
  height: 0.5       
  lc_factor: 12     

material:
  youngs_modulus_range: [10.0, 210.0]
  poissons_ratio_range: [0.2, 0.45]

model:
  input_dim: 7      
  hidden_dim: 32   # Réduit de 64 à 32 pour économiser la VRAM
  layers: 12        # Réduit de 10 à 6 (plus stable pour la mémoire)

training:
  epochs: 50             
  batch_size: 16     # RÉDUIT de 32 à 4 (Indispensable pour ta GPU 6Go)
  learning_rate: 0.001    
  data_weight: 1.0        
  physics_weight: 0.5    

env:
  device: "cuda"          
  save_path: "./models"
